baseURL: "https://blog.sujaykumarh.com/"
languageCode: "en-us"
title: "Blog | sujaykumarh"

paginate: 5
theme: paper

####
## Hugo Options
####

# Disable unwanted features
disableKinds:
  - RSS
  - taxonomy
  - term

disableHugoGeneratorInject: "true"

####
## Theme Options
####

googleAnalytics: "G-RDJM8E8822"
enableRobotsTXT: false
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true

pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

copyright: "&copy; [sujaykumarh](https://sujaykumarh.com/?utm_source=blog&utm_medium=footer&utm_campaign=social) |"

params:
  # to enable google analytics, opengraph, twitter-cards and schema.
  env: production 
  title: Blog
  description: "sujaykumarh blog"
  keywords: [Blog, sujaykumarh]
  author: sujaykumarh
  # author: ["Me", "You"] # multiple authors
  images: ["#"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    # to disable highlight.js
    disableHLJS: true
    disableFingerprinting: true

    favicon: "https://github.com/sujaykumarh.png"
    favicon16x16: "https://github.com/sujaykumarh.png?size=16"
    favicon32x32: "https://github.com/sujaykumarh.png?size=32"
    apple_touch_icon: "https://github.com/sujaykumarh.png?size=128"
    safari_pinned_tab: "https://github.com/sujaykumarh.png?size=128"

  label:
    text: "Blog | sujaykumarh"
    icon: https://github.com/sujaykumarh.png
    iconHeight: 35

  # profile-mode
  profileMode:
    # needs to be explicitly set
    enabled: false 
    title: Blog
    subtitle: "Hi there 👋 welcome to my blog"
    imageUrl: "https://github.com/sujaykumarh.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there 👋"
    Content: Welcome to my blog

  socialIcons:
    - name: website
      url: "https://sujaykumarh.com/?utm_source=blog&utm_medium=social&utm_campaign=social"
    - name: github
      url: "https://github.com/sujaykumarh"
    - name: twitter
      url: "https://twitter.com/sujaykumarh"
    - name: KoFi
      url: "https://ko-fi.com/sujaykumarh"
    - name: buymeacoffee
      url: "https://buymeacoffee.com/sujaykumarh"

  analytics:
    google:
      SiteVerificationTag: "G-RDJM8E8822"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # # for search
  # # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]
  
menu:
  main:
    - name: Archive
      identifier: archives
      url: archives      
      weight: 10
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20



# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
